config/routes.rb
Rails.application.routes.draw do
  resources :vecinos
  get 'welcome/index'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  
  get '/users' => 'vecinos#index', as: :user_root
  
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable and :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :vecinos
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/models/vecino.rb
class Vecino < ApplicationRecord
  belongs_to :user
  validates_presence_of :name
  validates_presence_of :street
  validates_presence_of :house_number
  validates_presence_of :zip_code,
                        format: { with: /\d{5}/}
  validates :phone, presence: true,
            format: { with: /\d{10}/}
  #attr_accessor :name, :street, :house_number, :zip_code; :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {
      |u| u.permit(:name, :email, :password, :zip_code, :colonia)
    }
    devise_parameter_sanitizer.permit(:account_update) {
      |u| u.permit(:name, :email, :password, :current_password, :zip_code, :colonia)
    }
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include GetColoniasHelper
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # POST /resource/
   def new
       @colonias = get_colonias
       super
   end

  # GET /resource/edit
   def edit
     @colonias = get_colonias
     super
   end

  # PUT /resource
   def update
     super do
       @colonias = get_colonias
     end
   end

   def update_resource(resource, params)
     if current_user.provider == "facebook"
       params.delete("current_password")
       resource.update_without_password(params)
     else
       resource.update_with_password(params)
     end
   end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/vecinos_controller.rb
class VecinosController < ApplicationController
  before_action :authenticate_user!
  #skip_before_action :verify_authenticity_token
  #index show new edit update destroy

  def index
    @vecinos = current_user.vecinos
  end
  
  def show
    @vecino = Vecino.find(params[:id])
    @map = 	"https://www.google.com/maps/embed/v1/place?key=AIzaSyDmYN3xQvXMDAjZapUHgLcjAIu69lC1QJ8&q=#{@vecino.house_number}+Calle+#{@vecino.street}+#{@vecino.zip_code}"
  end
  
  def new
    @vecino = Vecino.new
  end

  def edit
    @vecino = Vecino.find(params[:id])
  end

  def create
    @vecino = current_user.vecinos.create(vecino_params)
    
    if @vecino.save
      redirect_to @vecino
    else
      render 'new'
    end
  end
  
  def update
    @vecino = Vecino.find(params[:id])
    
    if @vecino.update(vecino_params)
      redirect_to @vecino
    else
      render 'edit'
    end
  end

  def destroy
    @vecino = Vecino.find(params[:id])
    @vecino.destroy

    redirect_to vecinos_path
  end
  private
  def vecino_params
    params.require(:vecino).permit(:name, :phone, :house_number, :street, :zip_code)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_colonias_helper.rb
module GetColoniasHelper
  def get_colonias
    path = "#{Rails.root}/app/assets/data/cdmx_colonias.xml"
    doc = Nokogiri::XML(File.read(path), nil, 'UTF-8').remove_namespaces!
    @colonias = doc.xpath("//table").map{ |item| item.at('d_asenta').text}
    #@colonias=doc.xpath("//table").map{ |item| {item.at('d_codigo').text => item.at('d_asenta').text}}
    # array= doc.css("table").map{ |cp| [cp.at('d_codigo'), cp.at('d_asenta')].map(&:text)}
    # @colonias = Hash.new{ |h,k| @colonias[k]=[] }
    # array.each { |k,v| @colonias[k] << v}
  end
end

app/helpers/vecinos_helper.rb
module VecinosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vecino</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>
  <div>
	<%= link_to '', root_path, class: "btn btn-primary glyphicon glyphicon-home" %>
	<span class="text-info">
	  <% if user_signed_in? %>
	  <%= link_to '', destroy_user_session_path, method: :delete, data: { confirm: "Esta seguro que quiere cerrar sesion?" }, class: "btn btn-primary glyphicon glyphicon-off" %>
	  <strong>Usuario: </strong><%= current_user.name.split[0].capitalize%>
	  <%= link_to '', edit_user_registration_path, class: "glyphicon glyphicon-cog"%>
	  <% end  %>
	</span>
  </div>
  <body>
	<div class="container">
	  <p class="notice"><%= notice  %></p>
	  <p class="alert"><%= alert %></p>
	</div>
    <%= yield %>
  </body>
  <script>
	window.fbAsyncInit = function() {
	FB.init({
	appId      : '{your-app-id}',
	cookie     : true,
	xfbml      : true,
	version    : '{latest-api-version}'
	});

	FB.AppEvents.logPageView();

	};

	(function(d, s, id){
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) {return;}
	js = d.createElement(s); js.id = id;
	js.src = "https://connect.facebook.net/en_US/sdk.js";
	fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
  </script>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/vecinos/_form.html.erb
<div class="container"><%= link_to "Regresar", vecinos_path, class: "btn btn-primary glyphicon glyphicon-chevron-left" %></div>
<br>
<div class="container ">
  <%= form_with model: @vecino, local: true  do |form| %>
  <% if @vecino.errors.any? %>
  <div class="text-danger" id="error_explanation" class: "form-inline">
	<ul class="list-group">
	  <% @vecino.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	  <% end %>
	</ul>
  </div>
  <% end %>

  <p>
	<%= form.label "Nombre Completo" %>
	<%= form.text_field :name, class: "form-control", style: "width:210px;", placeholder: "Pepito Perez" %>
	<%= form.label :phone, "Telefono de casa" %>
	<%= form.text_field :phone, class: "form-control", style: "width:110px;", placeholder: "0123456789"%>
  </p>
  <p>
  	<%= form.label "Numero"%>
  	<%= form.number_field :house_number, class: "form-control", style: "width:60px;", placeholder: "111"%>
  	<%= form.label "Calle" %>
  	<%= form.text_field :street, class: "form-control", style: "width:400px;", placeholder: "Calle 23"%>
  	<%= form.label "Codigo postal"%>
  	<%= form.number_field :zip_code, class: "form-control", style: "width:85px;", placeholder: "07865"%>
  </p><br><br>
	<%= form.submit class: "btn btn-primary"%>
	<% end %>
</div>

app/views/vecinos/index.html.erb
<div class="container"><%= link_to "Regresar", root_path, class: "btn btn-primary glyphicon glyphicon-chevron-left" %></div>
<h1 class="container"><%= "Colonia #{current_user.colonia}" || "La colonia"%></h1>
<br>
<div class="container" style="text-align:left;">
	<%= link_to ' Agregar', new_vecino_path, class: "btn btn-sm btn-default glyphicon glyphicon-plus" %>
</div>

<div class="container">
  <table class="table table-bordered table-striped">
	  <tr class="bg-info">
		<th></th>
		<th>Nombre</th>
	  </tr>

	<% @vecinos.each do |v| %>
	<tr>
	  <td style="width:140px; text-align: center">
		<%= link_to  '' ,vecino_path(v), class: "btn btn-sm btn-default glyphicon glyphicon-eye-open text-primary" %>
		<%= link_to '', edit_vecino_path(v), class: "btn btn-sm btn-default glyphicon glyphicon-edit" %>
		<%= link_to '', vecino_path(v), class: "btn btn-sm btn-default glyphicon glyphicon-trash" ,
												method: :delete, data: { confirm: "Esta seguro que quiere borrar a #{v.name.split()[0]} de su lista?" } %>
	  </td>
	  <td><%= v.name %></td>
	</tr>
	<% end %>
  </table>
</div>
<hr>

app/views/welcome/index.html.erb
<style type="text/css">
  body {
  background: url('/assets/fondo.png');
  height: 100%;
  background-repeat: no-repeat;
  background-size: cover;
  }
</style>
<body>
  <div class="container">
	<h1 class="text-left"><strong>VECINO</strong></h1>
	<br>
	<div class="jumbotron">
	  <p> Vecino es una aplicación web que te permite crear una red de vecinos comunicados en tu colonia. </p>
	</div>
	<div class="nav" style="width:11%;">
	  <% if user_signed_in? %>
	  <li class="nav-item">
		<%= link_to('Desconectarse', destroy_user_session_path, method: :delete) %>
		<% else %>
	  <li class="nav-item">
		<%= link_to('Iniciar sesion', new_user_session_path) %>
	  <li class="nav-item">
		<%= link_to('Crear cuenta', new_user_registration_path)  %>
		<% end %>
	  <li class="nav-item">
		<%= link_to 'Ver la colonia', controller: 'vecinos' %>
	</div>

	<br>
  </div>
</body>